### ISSUE TITLE
unable to publish repo, suspect it's because of "/" in package name

### ISSUE THREAD

**Issue by ericblade** [RollingVersions/RollingVersions#215]
package is @ericblade/quagga2

publishing has been failing for a while, investigating into it, i discovered there were some changes that needed to be made due to some recent changes server side.  It took me a bit, but I managed to figure them out.. 

and now i'm getting

````
publishing @ericblade/quagga2 to npm @ 1.5.0
Error: npm publish exited with code 1:
npm notice 
npm notice 📦  @ericblade/quagga2@1.5.0
npm notice === Tarball Contents === 
npm notice 1.1kB   LICENSE                     
npm notice 1.6MB   dist/quagga.js              
npm notice 1.5MB   lib/quagga.js               
npm notice 135.8kB dist/quagga.min.js          
npm notice 6.7kB   package.json                
npm notice 2.1kB   tsconfig.json               
npm notice 6.8kB   CHANGELOG.md                
npm notice 31.9kB  README.md                   
npm notice 27.6kB  type-definitions/quagga.d.ts
npm notice === Tarball Details === 
npm notice name:          @ericblade/quagga2                      
npm notice version:       1.5.0                                   
npm notice package size:  807.1 kB                                
npm notice unpacked size: 3.3 MB                                  
npm notice shasum:        e55f06f887d6d78c274a5fdc15d6e9b00d685238
npm notice integrity:     sha512-eFRJjv5x4I8WL[...]GhAAcgiMO6/uA==
npm notice total files:   9                                       
npm notice 
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/@ericblade%2fquagga2 - Not found
npm ERR! 404 
npm ERR! 404  '@ericblade/quagga2@1.5.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-03-05T08_09_34_040Z-debug.log

    at spawnBuffered (/home/runner/.npm/_npx/2028/lib/node_modules/rollingversions/src/utils/spawn.ts:34:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at publish$2 (/home/runner/.npm/_npx/2028/lib/node_modules/rollingversions/src/services/npm/index.ts:165:3)
    at /home/runner/.npm/_npx/2028/lib/node_modules/rollingversions/src/PublishTargets/npm.ts:[46](https://github.com/ericblade/quagga2/runs/5431822013?check_suite_focus=true#step:5:46)7:9
    at withNpmVersion (/home/runner/.npm/_npx/2028/lib/node_modules/rollingversions/src/PublishTargets/npm.ts:161:14)
    at Object.publish (/home/runner/.npm/_npx/2028/lib/node_modules/rollingversions/src/PublishTargets/npm.ts:461:5)
    at Object.publish (/home/runner/.npm/_npx/2028/lib/node_modules/rollingversions/src/PublishTargets/baseTarget.ts:171:9)
    at publish$1 (/home/runner/.npm/_npx/2028/lib/node_modules/rollingversions/src/PublishTargets/index.ts:133:7)
    at publish (/home/runner/.npm/_npx/2028/lib/node_modules/rollingversions/src/commands/publish.ts:2[49](https://github.com/ericblade/quagga2/runs/5431822013?check_suite_focus=true#step:5:49):7)
Error: Process completed with exit code 1.
````

a manual publish succeeds, and looks like
````
C:\src\quagga2>npm publish
npm notice 
npm notice 📦  @ericblade/quagga2@1.5.0
npm notice === Tarball Contents ===
npm notice 1.2kB   LICENSE
npm notice 32.8kB  README.md
npm notice 1.6MB   dist/quagga.js
npm notice 135.8kB dist/quagga.min.js
npm notice 1.5MB   lib/quagga.js
npm notice 6.9kB   package.json
npm notice 2.2kB   tsconfig.json
npm notice 28.5kB  type-definitions/quagga.d.ts
npm notice === Tarball Details ===
npm notice name:          @ericblade/quagga2
npm notice version:       1.5.0
npm notice filename:      @ericblade/quagga2-1.5.0.tgz
npm notice package size:  800.1 kB
npm notice unpacked size: 3.3 MB
npm notice shasum:        f641ff358bb84e60738206901feddc793c056595
npm notice integrity:     sha512-sDJXK/lUisubX[...]2SOoWUbi03GyA==
npm notice total files:   8
npm notice
+ @ericblade/quagga2@1.5.0
````

**Comment by ForbesLindesay** [comment]
I think this is an issue with how npm is configured in GitHub actions, rather than with Rolling Versions itself. All Rolling Versions is doing here is updating the `package.json` file with the new version and then running `npm publish` in that directory.

Looking at the workflow you are using to publish: https://github.com/ericblade/quagga2/blob/a3a35dd2f280c4584697c1ca15c13f0ef07646d9/.github/workflows/publish.yml#L14-L32 I think it's the setup-node step that may be causing issues. You are using the v1 version of the setup-node action, which requires you to explicitly set the registry-url if you need to publish to npm.

I think it should work if you update your yaml for that workflow to:

```diff
  name: Deploy New Version

  on:
    repository_dispatch:
      types: [rollingversions_publish_approved]

  jobs:
    build:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
+         registry-url: 'https://registry.npmjs.org'
-       env:
-         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: npm install, build, test, publish
        run: |
          node --version
          npm --version
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: rollingversions check
        run: npx rollingversions publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

I've submitted a pull request with this change: https://github.com/ericblade/quagga2/pull/406

**Comment by ericblade** [comment]
looks like that did it for this one, thank you!
